import '../models/domain.dart';
import '../utils/format_utils.dart';

class _BlockedRange {
  final int start;
  final int end;
  const _BlockedRange(this.start, this.end);
}

final RegExp _lineRe = RegExp(
  r'(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s*[-–—to]+\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)?',
  caseSensitive: false,
);

int _timeToMin(String h, String? m, String? period) {
  var hour = int.parse(h) % 12;
  if (period != null && period.toLowerCase() == 'pm') hour += 12;
  return hour * 60 + int.parse(m ?? '0');
}

List<_BlockedRange> _parseCommitments(String raw) {
  if (raw.trim().isEmpty) return [];
  final ranges = <_BlockedRange>[];
  for (final line in raw.split('\n')) {
    final m = _lineRe.firstMatch(line);
    if (m == null) continue;
    final h1 = m.group(1)!;
    final m1 = m.group(2);
    final p1raw = m.group(3);
    final h2 = m.group(4)!;
    final m2 = m.group(5);
    final p2raw = m.group(6);

    final p2 = p2raw ?? p1raw ?? 'pm';
    String p1 = p1raw ?? p2;
    // إضافة الشرط الذكي لاكتشاف تداخل الصباح/المساء
    if (p1raw == null && p2 == 'pm' && int.parse(h1) > int.parse(h2)) {
      p1 = 'am';
    }

    final start = _timeToMin(h1, m1, p1);
    var end = _timeToMin(h2, m2, p2);
    if (end <= start) end += 12 * 60;
    ranges.add(_BlockedRange(start, end > 24 * 60 ? 24 * 60 : end));
  }
  return ranges;
}

/// Lines in the commitments box that _parseCommitments couldn't turn into
/// a blocked time range — e.g. "Meeting at 3" (no end time) or "Call with
/// advisor" (no time at all). Those commitments were previously ignored
/// with zero feedback: they didn't block anything, and the generator
/// could (and did) schedule a priority block right on top of them. Meant
/// to be checked live as the person types, so they can see and fix a line
/// before generating instead of only finding out by comparing the result
/// against what they meant to type.
List<String> findUnparsedCommitmentLines(String raw) {
  final unparsed = <String>[];
  for (final rawLine in raw.split('\n')) {
    final line = rawLine.trim();
    if (line.isEmpty) continue;
    if (_lineRe.firstMatch(line) == null) unparsed.add(line);
  }
  return unparsed;
}

List<NewTask> generateScheduleFromInputs(
  List<String> priorities,
  double focusHours,
  List<Task> existingTasksForDate,
  String commitmentsRaw,
  String targetDate, {
  String focusBlockFallback = 'Focus block',
  String breakLabel = 'Break',
  String continuedSuffix = ' (cont.)',
  String generatedByNote = 'Generated by Plan My Day',
  // BUG FIX: this used to always start planning at 9 AM regardless of
  // what time it actually was. Used on today with the current time past
  // 9 AM, every generated block landed in the past — freshly-created
  // "to do" tasks that were already "overdue" the instant they appeared.
  // Callers building a plan for *today* should pass the current
  // minutes-since-midnight here; the generator then starts at whichever
  // is later, 9 AM or now (rounded up to the next 15-minute mark so the
  // first block doesn't start at some odd minute like 2:37). Leave this
  // null when targetDate isn't today — there's no "now" to respect for a
  // future day, so 9 AM stands as the default start.
  int? notBeforeMinutes,
  // One category per priority, same order/length as `priorities` — falls
  // back to TaskCategory.work for any priority beyond the list (or if
  // omitted entirely) so this stays backward compatible. Previously every
  // generated block was hardcoded to TaskCategory.study regardless of
  // what the priority actually was, which skewed the Analytics category
  // breakdown for anyone whose priorities weren't study-related.
  List<TaskCategory>? categories,
}) {
  final totalFocusMinutes = (focusHours * 60).round();
  final list = priorities.isNotEmpty ? priorities : [focusBlockFallback];
  final perTask =
      clampInt((totalFocusMinutes / list.length).floor(), 30, 1 << 30);

  final blockedRanges = <_BlockedRange>[
    ..._parseCommitments(commitmentsRaw),
    ...existingTasksForDate
        .where((t) => t.status != TaskStatus.skipped)
        .map((t) => _BlockedRange(t.start, t.start + t.duration)),
  ]..sort((a, b) => a.start.compareTo(b.start));

  const dayEnd = 23 * 60;

  int advancePastBlocked(int cursor, int neededMinutes) {
    var c = cursor;
    var moved = true;
    while (moved) {
      moved = false;
      for (final b in blockedRanges) {
        if (c < b.end && c + neededMinutes > b.start) {
          c = b.end;
          moved = true;
        }
      }
    }
    return c;
  }

  final blocks = <NewTask>[];
  final roundedNow =
      notBeforeMinutes == null ? 0 : ((notBeforeMinutes + 14) ~/ 15) * 15;
  final earliestStart = roundedNow > 9 * 60 ? roundedNow : 9 * 60;
  var cursor = advancePastBlocked(earliestStart, 15);

  for (var i = 0; i < list.length; i++) {
    final title = list[i];
    final category = (categories != null && i < categories.length)
        ? categories[i]
        : TaskCategory.work;
    var remaining = perTask;
    while (remaining > 0 && cursor < dayEnd) {
      final chunk = remaining < 90 ? remaining : 90;
      cursor = advancePastBlocked(cursor, chunk);
      if (cursor >= dayEnd) break;
      blocks.add(NewTask(
        title:
            list.length > 1 && remaining != perTask ? '$title$continuedSuffix' : title,
        category: category,
        priority: i == 0 ? TaskPriority.high : TaskPriority.medium,
        status: TaskStatus.todo,
        start: cursor,
        duration: chunk,
        notes: generatedByNote,
        taskDate: targetDate,
      ));
      cursor += chunk;
      remaining -= chunk;
      if (remaining > 0) {
        cursor = advancePastBlocked(cursor, 10);
        blocks.add(NewTask(
          title: breakLabel,
          category: TaskCategory.personal,
          priority: TaskPriority.low,
          status: TaskStatus.todo,
          start: cursor,
          duration: 10,
          notes: '',
          taskDate: targetDate,
        ));
        cursor += 10;
      }
    }
    if (i < list.length - 1 && cursor < dayEnd) {
      cursor = advancePastBlocked(cursor, 15);
      blocks.add(NewTask(
        title: breakLabel,
        category: TaskCategory.personal,
        priority: TaskPriority.low,
        status: TaskStatus.todo,
        start: cursor,
        duration: 15,
        notes: '',
        taskDate: targetDate,
      ));
      cursor += 15;
    }
  }

  return blocks;
}
